import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 18.0

[font.normal]
# family = "SauceCodePro Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5
